### ISSUE TITLE
No choice of installation path

### ISSUE THREAD

**Issue by Darthagnon** [onlineth/Spotlight-Desktop#19]
Would a choice of installation path in the MSI be possible, or a portable release? I hate it when programs install themselves without giving me a choice, and even more so when they install to weird locations like %AppData%

(I imagine I probably could just extract the program from the MSI with UniExtract2, but others might not be so knowledgeable).

**Comment by onlineth** [comment]
Sure, again the idea was to make this a minimal quick install for all users:) I would disagree with `%AppData%` being a weird location since major software development teams from Spotify, Slack, Discord, and Chrome have decided to install there.

Being that it is an MSI package, you can override where it installs via the command line. [This answer from StackOverflow](https://stackoverflow.com/a/8841965/2934528) explains how to install to a custom directory and more detailed usage of msiexec can be seen [here](https://docs.microsoft.com/en-us/windows/desktop/Msi/command-line-options).
