### ISSUE TITLE
High RAM usage, for what it does?

### ISSUE THREAD

**Issue by Darthagnon** [onlineth/Spotlight-Desktop#20]
(Measurements taken with Process Hacker - Private WS [Private bytes])
For a program that copies single images, very occasionally, between local directories, 5.35MB [12.96MB] feels like a lot of RAM to use. For comparison, 
 - ThrottleStop (CPU undervolting and advanced controls) takes 624kB  [3.45MB], 
 - Clover (Windows Explorer tabs) takes 3.87MB [5.62MB]
 - 7+ Taskbar Tweaker takes 1.8MB [2.54MB]
 - voidtools' Everything Search x64 (with extra indexing features disabled) takes 41.72MB [47.37MB] + 1.37MB [1.89] for the service

**Comment by onlineth** [comment]
That's due to the libraries imported to the project. [Here](https://github.com/onlineth/Spotlight-Desktop/tree/master/Spotlight%20Desktop) you will find the source code for the project. As you can see, only libraries that were needed were used. When compiled and executed, it usually loads around 5mb.

I am not sure how the other tools are developed. Some languages will use more ram than others (ie. Python vs C++). If you have any tricks with compliling this project or see some ways that the code could be trimed down with keeping the same functionality, I would be gracious for any PR. I am quite happy myself at where it's running now and would consider this very low memory usage comparatively,

![image](https://user-images.githubusercontent.com/7810121/44634328-00c91c00-a95e-11e8-9990-ff2206e31d95.png)
