### ISSUE TITLE
Virus false positive?

### ISSUE THREAD

**Issue by badbob001** [onlineth/Spotlight-Desktop#9]
AVG quarantine's 'SpotlightDesktop Launcher.exe' and virustotal shows some positive results:
https://www.virustotal.com/#/file/e5137694476ee9e94b957dfbb0b3d84c7068c1870e9cf36c356336bb1f5ac5db/detection

**Comment by onlineth** [comment]
Ya, Windows Defender, as well as other Virus scanners, say it's a virus. See https://github.com/onlineth/Spotlight-Desktop/issues/5#issuecomment-339382879.

Unfortunately, the way to access some of the registry keys (still a mystery to me of why I can't access these in the app itself) and the launcher which you stated is compiled from a bat to exe application. Bat to exe applications to my limited knowledge are notorious for simple hacks.

https://github.com/onlineth/Spotlight-Desktop/blob/master/SpotlightDesktop%20Launcher.bat
https://github.com/onlineth/Spotlight-Desktop/blob/master/RegLookup.bat

I would like to get a code signing certificate which would remove 99% of these alerts but as of now, they're a bit too expensive for me to purchase for such a small issue.

Now if anyone wants to make these themselves, I can provide instructions on how to compile these applications because I know if I saw these messages, I too would be kind of suspicious.

**Comment by onlineth** [comment]
This possibly is resolved, https://www.microsoft.com/en-us/wdsi/submission/eefe6314-584a-44b6-8966-290f41c7331a
